pool:  
  name: local 

trigger: none 

steps: 
- script: echo Hello, world! 
  displayName: 'Run a one-line script'
- task: Npm@1
- task: Maven@4
  inputs:
    mavenPomFile: 'gamesense.cloud/demo/'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'Path'
    mavenVersionOption: 'Path'
    mavenSetM2Home: false
    mavenAuthenticateFeed: true
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'h4xrOx'
- task: IISWebAppDeploymentOnMachineGroup@0
  inputs:
    WebSiteName: 'gamesense.cloud'
    Package: '$(System.DefaultWorkingDirectory)\**\*.zip'
    repositoryName: 'h4xrOx/gamesense.cloud'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
  inputs:
    command: 'install'
    verbose: true
    customRegistry: 'useFeed'
    customFeed: '57608194-7fe0-4de4-863f-2ccb84e6b54c'
