- task: Npm@1
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'h4xrOx'
    repositoryName: 'h4xrOx/gamesense.cloud'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
  inputs:
    command: 'install'
    verbose: true
    customRegistry: 'useFeed'
    customFeed: '57608194-7fe0-4de4-863f-2ccb84e6b54c'
